version: "3"
services:
  backend:
    build: ./Backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=your_mongodb_atlas_url
    depends_on:
      - frontend

  frontend:
    build: ./Frontend
    ports:
      - "3000:80"
